### ISSUE TITLE
Feature request: Implementation of interpolation methods for non-equidistant samples

### ISSUE THREAD

**Issue by BeneSeePTB** [PTB-PSt1/PyDynamic#30]
Some digital sensors generate their own sample clock. This clock fluctuates considerably which leads to not equidistant sample distances. FFT, DFT and wavelet transformations need equidistant samples, so it would be nice if PyDynamic could implement interpolation methods with error poropagation. 

Beste regards Benedikt

**Comment by BjoernLudwigPTB** [comment]
Thanks for the valuable input! We are about to begin implementation of a function *make_equidistant(**t**, **y**, **u<sub>y</sub>**, **dt** = none, **kind**='previous')*, where

-   **t** is the vector of timestamps,
-   **y** is the vector of values,
-   **u<sub>y</sub>** is the corresponding uncertainty,
-   **dt** denotes the distance between samples and
-   **kind** specifies the kind of interpolation as a string in accordance with [scipy.interpolate.interp1d](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp1d.html#scipy.interpolate.interp1d).

@BeneSeePTB: What do you think?

**Comment by BjoernLudwigPTB** [comment]
Will be finished by the end of this week with linear interpolation of the measurement values.

**Comment by BjoernLudwigPTB** [comment]
@BeneSeePTB The linear interpolation as well as the trivial cases *previous*, *next* and *nearest* are ready in PR #38 and will be merged and released shortly. I am up to cubic spline interpolation in the mean while or in parallel but will not wait for it. As soon, as @mgrub and me find the time to review the code of the PR it will be out.

**Comment by BjoernLudwigPTB** [comment]
@BeneSeePTB Merged and [released](https://pypi.org/project/PyDynamic/). You can now do
```
pip install PyDynamic --upgrade
```
and use it like described [here on ReadTheDocs](https://pydynamic.readthedocs.io/en/master/PyDynamic.misc.html#PyDynamic.misc.tools.make_equidistant).
