### ISSUE TITLE
Remove unused functions from tools

### ISSUE THREAD

**Issue by mgrub** [PTB-PSt1/PyDynamic#45]
Check which functions of [PyDynamic/misc/tools.py](https://github.com/eichstaedtPTB/PyDynamic/blob/master/PyDynamic/misc/tools.py) are not **used** (importing is not necessarily using) anywhere else in the PyDynamic-repo. 

Candidate function for removal are:
- col_hstack
- find
- zerom
- stack

Issue generated from in-code-TODOs, see #41

**Comment by eichstaedtPTB** [comment]
These functions exist from my early days with Python after moving from Matlab. Therefore, I recreated some functions that I was used to apply regularly. However, over time I replaced these with proper Python code. Hence, they can and should _all_ be deleted now.
