### ISSUE TITLE
Implement formula for colored noise

### ISSUE THREAD

**Issue by mgrub** [PTB-PSt1/PyDynamic#48]
In [uncertainty.propagate_filter.FIRuncFilter](https://github.com/eichstaedtPTB/PyDynamic/blob/master/PyDynamic/uncertainty/propagate_filter.py#L22) add possibility to change "color" of noise/uncertainty. 

Remarks:
- This functionality seems not to be covered by the underlying paper: http://dx.doi.org/10.1088/0026-1394/45/4/013 .

Issue generated from in-code-TODO, see #41

**Comment by eichstaedtPTB** [comment]
In the paper cited here the equation (15) denotes the auto-covariance of the inputs `x`; equation (32) denotes the calculation of the uncertainties for x_low using the autocovariances (15). In the current code, though, only white noise with ``sigma_noise`` being of type ``float``  is considered. 
Furthermore, for the output uncertainty ``U_y`` only the case of equation (33) is considered, but not (34).

**Comment by mgrub** [comment]
Draft Pull request: #55

**Comment by mgrub** [comment]
Next steps: 
- review new implementation with @eichstaedtPTB 
- if `isinstance(sigma_noise, float)`: maintain the probably more performant old implementations
