### ISSUE TITLE
Update graphic in Readme.md

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [PTB-PSt1/PyDynamic#62]
We should update the image ![PyDynamic modules](http://mathmet.org/projects/14SIP08/PyDynamic_scheme.png) and think about a workflow for doing so in the future (for example when we rename the modules while working on issue #31.

**Comment by eichstaedtPTB** [comment]
Will have a look to use draw.io

**Comment by eichstaedtPTB** [comment]
For now I have removed the old graphic from the Readme
