### ISSUE TITLE
Check 'if __name__ == "__main__":' part of signals.py for errors

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [PTB-PSt1/PyDynamic#64]
[`if __name__ == "__main__":` part of `signals.py`](https://github.com/PTB-PSt1/PyDynamic/blob/ac9a087bed85a3ec446148a72aefd856015472f5/PyDynamic/signals.py#L125) produces different errors on execution. We should find out the reason for those errors, resolve them and include the residual code parts into test suite.

**Comment by eichstaedtPTB** [comment]
I'd rather recommend to remove the whole statement from that module and create a new "example_signals_class.py" instead. Right now it's just a leftover from early testing.
