### ISSUE TITLE
The parameter b in misc.filterstuff.isstable is not used in the implementation

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [PTB-PSt1/PyDynamic#69]
The parameter `b` is denoted as [*filter numerator coefficients*](https://github.com/PTB-PSt1/PyDynamic/blob/c1bc48b8c4ba6af43e243d9d67681b6e5e05cab6/PyDynamic/misc/filterstuff.py#L137) in the according docstring, but not used at all during the implementation. Either we should include it in the implementation or remove it from the signature.

**Comment by eichstaedtPTB** [comment]
This method aims to use the same interface as the corresponding Matlab function. Hence, although b is not used in the code, it should be part of the function call.

**Comment by eichstaedtPTB** [comment]
@BjoernLudwigPTB Change docstring to Determine whether IIR filter (b,a) is stable by checking poles of the polynomial a (for digital filter) or location of its complex roots (for analogue filter).
